[tool.poetry]
name = "tg_crawler"
version = "0.1.0"
description = ""
authors = ["Andy"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Telethon = "^1.25.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
